language: java
jdk:
  - oraclejdk11
  - openjdk11

services: docker

branches:
  only:
    - master
    - develop

jobs:
  include:
    - stage: test code
      script:
        - chmod +x mvnw
        - ./mvnw test -B
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t cybersecmoo1/lime-auth:v$TRAVIS_BUILD_NUMBER .
        - docker tag cybersecmoo1/lime-auth:v$TRAVIS_BUILD_NUMBER registry.heroku.com/$HEROKU_APP/web
    - if: branch = master
      stage: deploy image
      script:
        - docker push cybersecmoo1/lime-auth:v$TRAVIS_BUILD_NUMBER
        - docker push registry.heroku.com/$HEROKU_APP/web
        - heroku container:release web --app $HEROKU_APP



