jobs:
  build:
    docker:
      - image: circleci/openjdk:11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw install -B
  test:
    docker:
      - image: circleci/openjdk:11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw test -B

  deploy:
    docker:
      - image: circleci/openjdk:11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
        version: 19.03.13
      - run:
          name: Build and push docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t cybersecmoo1/lime-auth:0.0.$CIRCLE_BUILD_NUM .
            docker tag cybersecmoo1/lime-auth:0.0.$CIRCLE_BUILD_NUM registry.heroku.com/$HEROKU_APP/web
            docker push cybersecmoo1/lime-auth:0.0.$CIRCLE_BUILD_NUM
            docker push registry.heroku.com/$HEROKU_APP/web
            heroku container:release web --app $HEROKU_APP
      - run:
          name: Deploy to Heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=$HEROKU_TOKEN heroku container:login
            HEROKU_API_KEY=$HEROKU_TOKEN heroku container:push -a lime-auth web
            HEROKU_API_KEY=$HEROKU_TOKEN heroku container:release -a lime-auth web
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master

