jobs:
  build:
    docker:
      - image: circleci/openjdk:11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw install -B
  test:
    docker:
      - image: circleci/openjdk:11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw test -B
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          requires:
            - test
