jobs:
  test:
    docker:
      - image: circleci/openjdk:11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: chmod +x mvnw
      - run: ./mvnw test -B

  deploy:
    docker:
      - image: circleci/openjdk:11
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: chmod +x mvnw
      - run: ./mvnw package -B
      - run:
          name: Build and push docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t cybersecmoo1/lime-auth:0.0.$CIRCLE_BUILD_NUM .
            docker push cybersecmoo1/lime-auth:0.0.$CIRCLE_BUILD_NUM
      - heroku/install
      - heroku/check-authentication
      - run: heroku login
      - run: heroku container:login
      - run: heroku container:push web -a $HEROKU_APP_NAME
      - heroku/release-docker-image
orbs:
  heroku: circleci/heroku@1.2.5
version: 2.1
workflows:
  build_and_test:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
                - main

